"""Canonical callback grammar + entity-addressed confirmations (B2: ARCH-04/05).

ARCH-04 — CALLBACK GRAMMAR
The stale-callback gate in the router extracts an optional flow id and flow
version from callback_data. The historical extractors were greedy: ANY
``:``-separated segment starting with ``f`` was read as a flow id (so
``flag:sleep:bad`` → flow id ``"lag"``, ``chk:state:fasting`` → ``"asting"``,
``menu:flags`` → ``"lags"``), which made those ordinary callbacks fail the
version check — and get refused as "stale" — whenever ANY flow was active.

The canonical grammar is defined by the only producer of these tokens,
``conversation.encode_callback``:

    <prefix>[:<part>...][:f<flow_id>][:v<version>]

where ``flow_id`` is always generated by ``conversation._new_flow_id`` as
``f-<user_id>-<12 hex>`` (so the encoded segment is ``ff-<user_id>-<hex>``)
and ``version`` is a small integer (encoded segment ``v<digits>``). Tokens
appear only as the FINAL segments. The strict extractors below therefore:

- only inspect the last two segments,
- match a flow token only as ``^ff-\\d+-[0-9a-f]{6,}$``,
- match a version token only as ``^v\\d{1,9}$``.

Ordinary payload segments (``flag``, ``fasting``, ``flags``, food names,
free values) can no longer be misread as correlation identity.

The extractors are installed OVER ``conversation.extract_version`` /
``conversation.extract_flow_id`` at application build time (the protected
router resolves them as module attributes at call time), preserving the
protected sources byte-identically.

ARCH-05 — ENTITY-ADDRESSED CONFIRMATIONS
``confirm:<kind>:<value>`` callbacks carry a RAW value and the handler used
to apply it unconditionally — a months-old "✅ אישור יעד" message could
re-activate a stale calorie goal. The confirmation gate wraps the menu
callback handler (facade attribute, same install pattern) and only lets a
``confirm:`` action through when it can be addressed to the entity the user
was actually shown:

1. ``confirm:cancel:*`` — always allowed (explicitly idempotent/safe).
2. A live pending confirmation (the ``confirm_number`` flow set by
   ``set_confirm_pending``) whose stored value matches the callback value —
   the strongest, fully server-side address.
3. Otherwise, render freshness: the pressed message resolves to a delivered
   render (O3 render registry) AND the confirmation's subject has not
   changed since that render was delivered (goal decided_at / fact
   updated_at compared against the render's delivery time). The user is
   confirming exactly what they can still see.
4. Anything else is REFUSED with a friendly message — a stale confirmation
   never silently mutates the newest entity. The refusal emits canonical
   ``validation.failed`` (entity=confirmation, outcome=stale).
"""

from __future__ import annotations

import re
from typing import Any

import conversation

# ---------------------------------------------------------------------------
# ARCH-04: strict grammar
# ---------------------------------------------------------------------------

_FLOW_TOKEN_RE = re.compile(r"^f(f-\d+-[0-9a-f]{6,})$")
_VERSION_TOKEN_RE = re.compile(r"^v(\d{1,9})$")


def strict_extract_version(data: str) -> int | None:
    """Version token per the canonical grammar: final-position ``v<digits>``."""
    for part in reversed(data.split(":")[-2:]):
        match = _VERSION_TOKEN_RE.match(part)
        if match:
            return int(match.group(1))
    return None


def strict_extract_flow_id(data: str) -> str | None:
    """Flow token per the canonical grammar: ``f`` + ``f-<uid>-<hex>``."""
    for part in reversed(data.split(":")[-2:]):
        match = _FLOW_TOKEN_RE.match(part)
        if match:
            return match.group(1)
    return None


_original_extract_version: Any = None
_original_extract_flow_id: Any = None


def install_callback_grammar() -> None:
    """Install the strict extractors over the conversation module attributes
    (the protected router resolves them at call time). Idempotent."""
    global _original_extract_version, _original_extract_flow_id
    if _original_extract_version is None:
        _original_extract_version = conversation.extract_version
        conversation.extract_version = strict_extract_version
    if _original_extract_flow_id is None:
        _original_extract_flow_id = conversation.extract_flow_id
        conversation.extract_flow_id = strict_extract_flow_id


def uninstall_callback_grammar() -> None:
    global _original_extract_version, _original_extract_flow_id
    if _original_extract_version is not None:
        conversation.extract_version = _original_extract_version
        _original_extract_version = None
    if _original_extract_flow_id is not None:
        conversation.extract_flow_id = _original_extract_flow_id
        _original_extract_flow_id = None


# ---------------------------------------------------------------------------
# ARCH-05: confirmation gate
# ---------------------------------------------------------------------------

# What each confirmation kind is ABOUT, for the render-freshness check:
# a confirmation is stale when its subject changed after the render that
# presented the button was delivered.
_KIND_SUBJECT = {
    "goal_cal": "goal",
    "weight": ("fact", "weight_kg"),
    "goal_weight": ("fact", "goal_weight"),
}


async def _pending_confirmation_matches(db: Any, user_id: int, value: float) -> bool:
    """Strongest address: the live confirm_number flow stores the exact value
    the user is being asked about (set_confirm_pending)."""
    try:
        flow = await conversation.get_active_flow(db, user_id)
    except Exception:  # noqa: BLE001
        return False
    if flow.name != conversation.FlowName.confirm_number:
        return False
    stored = flow.payload.get("value")
    try:
        return stored is not None and abs(float(stored) - value) < 1e-6
    except (TypeError, ValueError):
        return False


async def _subject_changed_at(db: Any, user_id: int, kind: str) -> str | None:
    """UTC iso timestamp of the confirmation subject's last change, if any."""
    subject = _KIND_SUBJECT.get(kind)
    if subject == "goal":
        row = await db.fetch_one(
            """
            SELECT MAX(COALESCE(decided_at, created_at)) AS changed_at
            FROM goal_versions WHERE user_id=?
            """,
            (user_id,),
        )
        return row["changed_at"] if row else None
    if isinstance(subject, tuple):
        _, fact_key = subject
        row = await db.fetch_one(
            "SELECT COALESCE(updated_at, created_at) AS changed_at "
            "FROM user_facts WHERE user_id=? AND key=? AND valid=1",
            (user_id, fact_key),
        )
        return row["changed_at"] if row else None
    return None


async def _render_is_fresh(db: Any, user_id: int, query: Any, kind: str) -> bool:
    """Rule 3: the pressed message resolves to a delivered render AND the
    confirmation subject has not changed since that render was delivered."""
    message = getattr(query, "message", None)
    message_id = getattr(message, "message_id", None)
    if message_id is None:
        return False
    try:
        import event_log
        from noam_coach.observability import taxonomy
        from noam_coach.observability.render_registry import find_render_for_message

        render = await find_render_for_message(db, user_id, message_id)
        if render is None:
            return False
        delivered = await event_log.list_events(
            db, user_id, event=taxonomy.DELIVERY_SUCCEEDED, limit=400
        )
        delivered_at = None
        for item in reversed(delivered):
            if item.properties.get("render_id") == render.render_id:
                delivered_at = item.created_at
                break
        if delivered_at is None:
            return False
        changed_at = await _subject_changed_at(db, user_id, kind)
        return changed_at is None or changed_at <= delivered_at
    except Exception:  # noqa: BLE001 — cannot prove freshness → not fresh.
        return False


async def _refuse_stale_confirmation(
    db: Any, query: Any, user_id: int, data: str, kind: str, reason: str
) -> None:
    try:
        from noam_coach.observability import taxonomy
        from noam_coach.observability.emit import emit_event

        await emit_event(
            db, user_id, taxonomy.VALIDATION_FAILED,
            entity="confirmation", entity_id=kind,
            source="confirmation_gate", status="failed", outcome="stale",
            properties={
                "callback_data": data[:64],
                "kind": kind,
                "reason": reason,
            },
        )
    except Exception:  # noqa: BLE001
        pass
    import coach_bot

    await coach_bot.safe_edit(
        query,
        "האישור הזה כבר לא בתוקף — הנתון השתנה מאז שההודעה נשלחה.\n"
        "אם עדיין רלוונטי, בקש שוב (למשל: \"תעדכן יעד ל-2100\").",
        coach_bot.home_keyboard(),
    )


_original_handle_menu_callback: Any = None


def install_confirmation_gate() -> None:
    """Wrap the menu-callback handler at the coach_bot facade (the protected
    router re-syncs it per call). Idempotent, uninstallable."""
    global _original_handle_menu_callback
    if _original_handle_menu_callback is not None:
        return
    import coach_bot

    _original_handle_menu_callback = coach_bot.handle_menu_callback
    # Bind the original into the closure: runtime_bound re-syncs facade
    # attributes into caller modules per call, so a synced copy of this
    # wrapper can outlive uninstall — it must keep working standalone
    # rather than reading mutable module globals.
    original = _original_handle_menu_callback

    async def gated_handle_menu_callback(query: Any, user_id: int, data: str) -> bool:
        if isinstance(data, str) and data.startswith("confirm:"):
            parts = data.split(":", 2)
            kind = parts[1] if len(parts) > 1 else ""
            if kind != "cancel" and kind in _KIND_SUBJECT:
                import coach_bot as facade

                db = facade.DB
                try:
                    value = float(parts[2])
                except (IndexError, TypeError, ValueError):
                    value = float("nan")
                if await _pending_confirmation_matches(db, user_id, value):
                    pass  # rule 2: live pending confirmation for this value
                elif await _render_is_fresh(db, user_id, query, kind):
                    pass  # rule 3: user confirms what they can still see
                else:
                    await _refuse_stale_confirmation(
                        db, query, user_id, data, kind,
                        reason="no_pending_match_and_render_stale_or_unresolved",
                    )
                    return True
        return await original(query, user_id, data)

    coach_bot.handle_menu_callback = gated_handle_menu_callback


def uninstall_confirmation_gate() -> None:
    global _original_handle_menu_callback
    if _original_handle_menu_callback is not None:
        import coach_bot

        coach_bot.handle_menu_callback = _original_handle_menu_callback
        _original_handle_menu_callback = None
